# Testing BrainPower AES System
#### The purpose of this notebook is to:
1. Test the ASR and OCR components to justify their inclusion in the AES pipeline to provide
   accessibility and inclusion
3. Test the Transformer component to determine its suitability for providing assistance to human scorers

#### The Prompt

In [2]:
prompt = """More and more people use computers, but not everyone agrees that this benefits society. 
    Those who support advances in technology believe that computers have a positive effect on people. 
    They teach hand-eye coordination, give people the ability to learn about faraway places and people, 
    and even allow people to talk online with other people. Others have different ideas. Some experts 
    are concerned that people are spending too much time on their computers and less time exercising, 
    enjoying nature, and interacting with family and friends. 

    Write a letter to your local newspaper in which you state your opinion on the effects computers have 
    on people. Persuade the readers to agree with you."""

#### Rubric Guidelines for ASAP 1.0 Dataset

In [3]:
import pandas as pd
df = pd.read_csv("./data/rubric guidelines.csv", encoding="utf-8")
df[:]

,score,description,typical element 1,typical element 2,typical element 3,typical element 4
0,1,An undeveloped response that may take a positi...,Contains few or vague details.,Is awkward and fragmented.,May be difficult to read and understand.,May show no awareness of audience.
1,2,An under-developed response that may or may no...,Contains only general reasons with unelaborate...,Shows little or no evidence of organization.,May be awkward and confused or simplistic.,May show little awareness of audience.
2,3,A minimally-developed response that may take a...,Has reasons with minimal elaboration and more ...,Shows some organization.,May be awkward in parts with few transitions.,Shows some awareness of audience.
3,4,A somewhat-developed response that takes a pos...,Has adequately elaborated reasons with a mix o...,Shows satisfactory organization.,May be somewhat fluent with some transitional ...,Shows adequate awareness of audience.
4,5,A developed response that takes a clear positi...,Has moderately well elaborated reasons with mo...,Exhibits generally strong organization.,May be moderately fluent with transitional lan...,May show a consistent awareness of audience.
5,6,A well-developed response that takes a clear a...,Has fully elaborated reasons with specific det...,Exhibits strong organization.,Is fluent and uses sophisticated transitional ...,May show a heightened awareness of audience.

#### Trait Level Annotations from ASAP++

In [4]:
df = pd.read_csv("./data/trait_level_annotations.csv", encoding="latin1")
df = df.fillna("")
df

,Traits,Trait Description,Score 1,Score 2,Score 3,Score 4,Score 5,Score 6,Note(s)
0,Ideas & Content,"This property checks for content, and ideas pr...",The writing lacks a central idea or purpose. T...,Main ideas and purpose are somewhat unclear or...,"The reader can understand the main ideas, alth...",The writing is clear and focused. The reader c...,"The writing is clear, focused and interesting....","The writing is exceptionally clear, focused, a...",In case of doubts: Since some of the ratings m...
1,Organization,This property checks how well structured the e...,The essay is awkward and fragmented. Ideas are...,Shows little or no evidence of organization.,The essay shows some organization. Its form ma...,The essay shows satisfactory organization. It ...,The essay shows good organization. There is a ...,The essay is well-organized. There is a clear ...,
2,Word Choice,,The writing shows an extremely limited vocabul...,"Language is monotonous and or misused, detract...","Language lacks precision and variety, or may b...",Words effectively convey the intended message....,Words convey the intended message in an intere...,Words convey the intended message in an except...,
3,Sentence Fluency,,The writing is difficult to follow or to read ...,The writing tends to be either choppy or rambl...,The writing tends to be mechanical rather than...,"The writing flows, however, connections betwee...",The writing has an easy flow and rhythm. Sente...,The writing has an effective flow and rhythm. ...,
4,Conventions,,"Numerous errors in usage, spelling, capitaliza...",The writing demonstrates little control of sta...,The writing demonstrates limited control of st...,The writing demonstrates control of standard w...,The writing demonstrates strong control of sta...,The writing demonstrates exceptionally strong ...,

#### Method for Feature Extraction and Accuracy Metrics

In [5]:
import nltk
nltk.download('punkt_tab')
from jiwer import wer, cer, process_words
import re
from pathlib import Path
import numpy as np
import copy


class EssayEditor: #4/aug/2026
    """This class normalizes a body of text and can display the body of text along with 
        its word and sentence counts.
    """
    #REGEX - compile patterns and rules once for efficiency
    REPLACEMENTS = {
        '/': ' or ',
        'slash': 'or',
        '@caps1': 'at caps one',
        '@caps2': 'at caps one',
        '@date1': 'at date one',
        '@organization1': 'at organization one',
        '@organization2': 'at organization two',
        'globe(astronomy)': 'globe astronomy',
    }
    SYMBOL_PATTERN = "|".join(re.escape(key) for key in REPLACEMENTS.keys())
    COMPILED_SYMBOL_PATTERN = re.compile(SYMBOL_PATTERN)
    PUNCTUATION_RULE = re.compile(r"[^\s\w]")#fina all characters that are not words or spaces
    SPACES_RULE = re.compile(r"\s+")#find all occurences of multiple spaces
    
    def __init__(self, text):
        self.text = text
        self.original_text=copy.copy(text)
        self.edit_log = []#stores record of successful exection
        self.is_normalised = False
        sentences = nltk.tokenize.sent_tokenize(self.text)
        sentence_count = len(sentences)
        #Taken prior to normalization which removes sentence punctuation
        self.sentence_count = sentence_count

    def normalise_text(self):
        self.text = self.text.lower()
        self.edit_log.append("Essay converted to lower case successfully.")
        # Normalise spoken forms and symbol
        self.text = self.COMPILED_SYMBOL_PATTERN.sub(
            lambda match: self.REPLACEMENTS[match.group(0)], 
            self.text
        )
        self.edit_log.append("Symbols and spoken forms normalized successfully.")
        #Clean text
        #Replace all non-words or non-spaces with an empty string
        self.text = self.PUNCTUATION_RULE.sub("", self.text)
        #Replace all spaces with a single space, then remove unwanted spaces
        self.text = self.SPACES_RULE.sub(" ", self.text).strip()        
        self.edit_log.append("Cleaned- punctuation an unwanted spaces removed successfully.")
        self.is_normalised = True

    def get_sentence_count(self):
        return self.sentence_count  
        
    def get_text(self) -> str:#use type hint
        """Returns normalised essay."""
        return self.text
        
    def get_word_count(self):
        words= nltk.tokenize.word_tokenize(self.text)
        words = [word for word in words if word.isalnum()]
        word_count= len(words)
        return word_count
        
    def show_normalised_text(self):
        print(self.text)  
        
    def show_original_text(self):
        print(self.original_text)
        
    def show_edit_log(self):
        if self.is_normalised:
            print("\nNormalised:")
            for i, log in enumerate(self.edit_log,1):
                print(f"{i}: {log}")
        else:
            print("\nEssay not normalised")
    def get_avg_logprob(self):
        pass
    def get_avg_confidence_score(self):
        pass
    def get_compression_ratio(self):
        pass

def get_files_metadata(path_to_folder):
    """This function returns a list of the paths, filenames and extensions for 
        all files in a folder.
        Path must be imported from pathlib
    """
    files_metadata = []
    #Folder with audio files
    folder = Path(path_to_folder)
    for file in folder.iterdir():#Returns Path object
        if file.is_file():
            #Get file path
            path = str(file)
            #Get file exension
            extension = file.suffix
            #Get file name/student's name
            name = file.stem
            #Get file size in bytes convert to mb
            size = round(file.stat().st_size/(1024**2), 2)
            #Add to list
            files_metadata.append({
                "path":path,
                "extension": extension,
                "name":name,
                "size":size
            })
    return files_metadata


def calculate_stats(list_of_nums):
    """This function takes as agrument and used numpy to  calculates, 
        the mean, median, min, max, std_dev of a list. It returns a
        dict. 
    """
    #Convert to numpy array
    vals= np.array(list_of_nums)
    stats = {
        #Calculate mean
        "mean": f"{vals.mean():.2%}",
        #Calculate median
        "median": f"{np.median(vals):.2%}",
        #Calculate min
        "min": f"{vals.min():.2%}",
        #Calculate max
        "max": f"{vals.max():.2%}",
        #Calculate std_dev
        "std_dev": f"{vals.std():.2%}"
    }
    return stats

# Calculate WER and CER -----------adapted from ChapGPT
def calculate_error_rates(reference_essay, component_output):
    word_error_rate = wer(reference_essay, component_output)
    character_error_rate = cer(reference_essay, component_output)
    return {
        "wer": word_error_rate, 
        "cer":character_error_rate
    }
    

class BatchDataOperator:
    """This class encapsulates:
        1) A list of detail dicts, each dict stores the file properties e.g. size, and extension 
            along with the wer, cer and the EssayEditor object initiated on, either the output 
            from the ASR or OCR component
        2) A wer_stats dict containing the statistical data with respect to the wer for the batch
        3) A cer_stats dict containing the statistical data with respect to the cer for the batch
        4) An eval_stats dict containing the statistical data with respect to pass/fail statuses 
            for the batch
    """
    def __init__(self):
        #Default WER and CER values
        self.wer_threshold = 0.090
        self.cer_threshold = 0.050
        self.details = []
    
        self.wer_stats = {
            "mean":'',
            "median":'',
            "min":'',
            "max":'',
            "std_dev":'',
        }
        self.cer_stats = {
            "mean":'',
            "median":'',
            "min":'',
            "max":'',
            "std_dev":'',
        }
        self.eval_stats = {    
            "wer passes": 0,
            "wer fails": 0,        
            "wer pass percentage": 0,        
            "wer fail percentage": 0,        
            "cer passes": 0,
            "cer fails": 0,
            "cer pass percentage":0,
            "cer fail percentage":0,
            "total passes": 0,
            "total fails": 0,
            "total pass percentage": 0,
            "total fail percentage": 0,
        }
        
    def set_wer_threshold(self, t):
        self.wer_threshold = t
        
    def set_cer_threshold(self, t):
        self.cer_threshold = t
                
    def save_detail(self, detail):
        """" Structure of a typical details object
            details = {
                "Student_ID": file["name"],
                "File Path": file["path"],
                "File Size": round(file['size'], 2),
                "File Length": duration,
                "File Extension":file["extension"],
                "EssayEditor": EssayEditor Object, 
                "WER": error_rates["wer"],
                "CER": error_rates["cer"],
                "Confidence Scores": confidence_scores_list,
                "Evaluation Status": evaluation_status
            }
        """
        self.details.append(detail)

    def show_wer_and_cer_stats(self):
        #Statistical Accuracy Statistics
        self.calculate_wer_and_cer_stats()
        statistics = {
            "WER": self.wer_stats,
            "CER": self.cer_stats
        }
        df = pd.DataFrame.from_dict(statistics)
        display(df)
        
    def show_eval_stats(self):
        # Pass and Fail Statistics
        self.calculate_eval_stats()
        df = pd.DataFrame.from_dict(self.eval_stats,orient="index", columns=["Batch Stats"])
        display(df)

    def show_threshold_performance(self):
        #Display transcription data
        self.details.sort(key=lambda item: item["WER"])
        df = pd.DataFrame(self.details, index=range(1, len(self.details)+1))
        df= df[[
                "Student_ID",
                "WER",
                "CER",
                "Evaluation Status"
        ]]
        display(df)       
 
    def calculate_wer_and_cer_stats(self):
        """Calculates the WER and CER statistics for the batch by:
            1) Looping through each detail dict in the details list
            2) Extracting the WER and CER values and storing them in appropriately named list
            3) Invoking numpy's statistical functions to obtain statistical measures
            4) Saving the returned values to the wer_stats and cer_stats dicts
        """
        wer_list=[] 
        
        #Store wer values from each details object in a list
        for details_obj in self.details:
            wer_list.append(details_obj["WER"])
            
        #Get WER stats 
        wer_stats = self.get_stats_for_list(wer_list)
        
        #Store wer statistics in wer_stats dict
        self.wer_stats["mean"] = wer_stats["mean"]
        self.wer_stats["median"] = wer_stats["median"]
        self.wer_stats["min"] = wer_stats["min"]
        self.wer_stats["max"] = wer_stats["max"]
        self.wer_stats["std_dev"] = wer_stats["std_dev"]
               
        cer_list=[] 
        
        #Store cer values from each details object in a list
        for details_obj in self.details:
            cer_list.append(details_obj["CER"])
            
        #Get CER stats 
        cer_stats = self.get_stats_for_list(cer_list)
        
        #Store wer statistics in wer_stats dict
        self.cer_stats["mean"] = cer_stats["mean"]
        self.cer_stats["median"] = cer_stats["median"]
        self.cer_stats["min"] = cer_stats["min"]
        self.cer_stats["max"] = cer_stats["max"]
        self.cer_stats["std_dev"] = cer_stats["std_dev"]
        
    def calculate_eval_stats(self):
        """Calculate pass and fail statistics for the whole batch"""
        batch_size = len(self.details)
        total_pass_percentage = f"{self.eval_stats['total passes'] / batch_size: .2%}"
        total_fail_percentage = f"{self.eval_stats['total fails'] / batch_size: .2%}"
        self.eval_stats['total pass percentage'] = total_pass_percentage
        self.eval_stats['total fail percentage'] = total_fail_percentage
        
        wer_fail_percentage = f"{self.eval_stats['wer fails'] / batch_size: .2%}"
        cer_fail_percentage = f"{self.eval_stats['cer fails'] / batch_size: .2%}"
        wer_pass_percentage = f"{self.eval_stats['wer passes'] / batch_size: .2%}"
        cer_pass_percentage = f"{self.eval_stats['cer passes'] / batch_size: .2%}"
        
        self.eval_stats['wer pass percentage'] = wer_pass_percentage
        self.eval_stats['wer fail percentage'] = wer_fail_percentage
        self.eval_stats['cer pass percentage'] = cer_pass_percentage
        self.eval_stats['cer fail percentage'] = cer_fail_percentage   
        
    def update_eval_stats(self, evaluation_status, error_rates):
        """Updates/Increments the pass and fail counts for the whole batch when passed
            the evalutation status  classification and error_rates tuple (wer, cer) 
            for a single component's(ocr/asr) output
        """
        if evaluation_status == "fail":#Either one or both wer/cer failed
            if error_rates["wer"] > self.wer_threshold and error_rates["cer"] <= self.cer_threshold: #wer failed, cer passed
                self.eval_stats["wer fails"] = self.eval_stats["wer fails"] + 1 
                self.eval_stats["cer passes"] = self.eval_stats["cer passes"] + 1 
            elif error_rates["wer"] <= self.wer_threshold and error_rates["cer"] > self.cer_threshold: #wer passed, cer failed
                self.eval_stats["wer passes"] = self.eval_stats["wer passes"] + 1 
                self.eval_stats["cer fails"] = self.eval_stats["cer fails"] + 1 
            else: #They both failed
                self.eval_stats["cer fails"] = self.eval_stats["cer fails"] + 1  
                self.eval_stats["wer fails"] = self.eval_stats["wer fails"] + 1  
            #Update total fail count
            self.eval_stats["total fails"] = self.eval_stats["total fails"] + 1 
        else: #The both passed
            self.eval_stats["cer passes"] = self.eval_stats["cer passes"] + 1  
            self.eval_stats["wer passes"] = self.eval_stats["wer passes"] + 1  
            self.eval_stats["total passes"] = self.eval_stats["total passes"] + 1 
        
    def get_stats_for_list(self, list_of_vals):
        """Takes as argument a list of values and uses numpy to  calculate, 
            the mean, median, min, max, std_dev of the list. It returns a
            dict. 
        """
        #Convert to numpy array
        vals= np.array(list_of_vals)
        stats = {
            #Calculate mean
            "mean": f"{vals.mean():.2%}",
            #Calculate median
            "median": f"{np.median(vals):.2%}",
            #Calculate min
            "min": f"{vals.min():.2%}",
            #Calculate max
            "max": f"{vals.max():.2%}",
            #Calculate std_dev
            "std_dev": f"{vals.std():.2%}"
        }
        return stats

    def show_representative_samples(self):
        """This function extracts the essays with the lowest WER, the higest WER, 
            the sample's median WER, and the medians of the lowest and the sample's median and the sample's median 
            and the highest WER. It then display, for each sample:
            -The student id
            -The WER
            -The CER
            -The Evaluation status
            -The normalised essay
        """
        min_indx = 0
        max_indx = len(self.details) -1 #Number of samples in batch
        median_indx = int((min_indx + max_indx)/2)
        lower_mid_indx = int((min_indx + median_indx)/2)
        upper_mid_indx = int((median_indx + max_indx)/2)
        

        sample_indx = [min_indx, lower_mid_indx, median_indx, upper_mid_indx, max_indx]
        
        for i in sample_indx:
            print(f"Student ID: {self.details[i]['Student_ID']}")
            print(f"WER: {self.details[i]['WER']:.2%}")
            print(f"CER: {self.details[i]['CER']:.2%}")
            print(f"Evaluation Status: {self.details[i]['Evaluation Status']}")
            self.details[i]["EssayEditor"].show_normalised_text() 
            print('\n')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\cowse\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

## Unit Testing

In [6]:
# UT001 - Importing the ASAP 1.0 dataset
df = pd.read_csv(
    "./data/asap/training_set_rel3.tsv",
    sep="\t",
    encoding="latin-1"
)
df.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5,4,NaN,9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4,3,NaN,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5,5,NaN,10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Get structure of dataset
df.columns.tolist()

['essay_id',
 'essay_set',
 'essay',
 'rater1_domain1',
 'rater2_domain1',
 'rater3_domain1',
 'domain1_score',
 'rater1_domain2',
 'rater2_domain2',
 'domain2_score',
 'rater1_trait1',
 'rater1_trait2',
 'rater1_trait3',
 'rater1_trait4',
 'rater1_trait5',
 'rater1_trait6',
 'rater2_trait1',
 'rater2_trait2',
 'rater2_trait3',
 'rater2_trait4',
 'rater2_trait5',
 'rater2_trait6',
 'rater3_trait1',
 'rater3_trait2',
 'rater3_trait3',
 'rater3_trait4',
 'rater3_trait5',
 'rater3_trait6']

In [8]:
#Get Statistics
df["essay_set"].value_counts().sort_index()

essay_set
1    1783
2    1800
3    1726
4    1770
5    1805
6    1800
7    1569
8     723
Name: count, dtype: int64

#### Extracting and Displaying Reference Essay

In [9]:
# UT002 - Extracting the first essay for the first prompt, then displaying it

#Extract essay
prompt1 = df[df["essay_set"] == 1].copy()
first_essay = prompt1.iloc[0]
reference_essay = first_essay["essay"]

#Create EssayEditor object
reference_essay = EssayEditor(reference_essay)

# Display reference essay
reference_essay.show_original_text()

Dear local newspaper, I think effects computers have on people are great learning skills/affects because they give us time to chat with friends/new people, helps us learn about the globe(astronomy) and keeps us out of troble! Thing about! Dont you think so? How would you feel if your teenager is always on the phone with friends! Do you ever time to chat with your friends or buisness partner about things. Well now - there's a new way to chat the computer, theirs plenty of sites on the internet to do so: @ORGANIZATION1, @ORGANIZATION2, @CAPS1, facebook, myspace ect. Just think now while your setting up meeting with your boss on the computer, your teenager is having fun on the phone not rushing to get off cause you want to use it. How did you learn about other countrys/states outside of yours? Well I have by computer/internet, it's a new way to learn about what going on in our time! You might think your child spends a lot of time on the computer, but ask them so question about the economy, sea floor spreading or even about the @DATE1's you'll be surprise at how much he/she knows. Believe it or not the computer is much interesting then in class all day reading out of books. If your child is home on your computer or at a local library, it's better than being out with friends being fresh, or being perpressured to doing something they know isnt right. You might not know where your child is, @CAPS2 forbidde in a hospital bed because of a drive-by. Rather than your child on the computer learning, chatting or just playing games, safe and sound in your home or community place. Now I hope you have reached a point to understand and agree with me, because computers can have great effects on you or child because it gives us time to chat with friends/new people, helps us learn about the globe and believe or not keeps us out of troble. Thank you for listening.

#### Reference Essay Feature Extraction

In [10]:
#Display Extracted Features - Word and Sentence Counts (from raw essay)
print(f"Number of words: {reference_essay.get_word_count()}")
print(f"Number of sentences : {reference_essay.get_sentence_count()}")

Number of words: 331
Number of sentences : 16

#### Calculating Character and Word Error Rates

In [11]:
#The essay below has been delebrately modified in a controlled manner to determine if 
#the WER and CER calculations are accurate. The digit '5' has been affixed to the ends
#of each of the first 3 and last 3 words of the essay.

modified_essay = """Dear5 local5 newspaper5, I think effects computers have on people are great learning skills/affects 
    because they give us time to chat with friends/new people, helps us learn about the globe(astronomy) and keeps us 
    out of troble! Thing about! Dont you think so? How would you feel if your teenager is always on the phone with friends! 
    Do you ever time to chat with your friends or buisness partner about things. Well now - there's a new way to chat the 
    computer, theirs plenty of sites on the internet to do so: @ORGANIZATION1, @ORGANIZATION2, @CAPS1, facebook, myspace 
    ect. Just think now while your setting up meeting with your boss on the computer, your teenager is having fun on the 
    phone not rushing to get off cause you want to use it. How did you learn about other countrys/states outside of yours? 
    Well I have by computer/internet, it's a new way to learn about what going on in our time! You might think your child 
    spends a lot of time on the computer, but ask them so question about the economy, sea floor spreading or even about the 
    @DATE1's you'll be surprise at how much he/she knows. Believe it or not the computer is much interesting then in class 
    all day reading out of books. If your child is home on your computer or at a local library, it's better than being out 
    with friends being fresh, or being perpressured to doing something they know isnt right. You might not know where your 
    child is, @CAPS2 forbidde in a hospital bed because of a drive-by. Rather than your child on the computer learning, 
    chatting or just playing games, safe and sound in your home or community place. Now I hope you have reached a point 
    to understand and agree with me, because computers can have great effects on you or child because it gives us time to 
    chat with friends/new people, helps us learn about the globe and believe or not keeps us out of troble. 
    Thank you5 for5 listening5."""

#Calculate Error Rates
error_rates = calculate_error_rates(reference_essay.get_text(), modified_essay)
print(f"Word Error Rate: {error_rates['wer']:.3f} \nCharacter Error Rate:{error_rates['cer']:.3f}")

Word Error Rate: 0.018
Character Error Rate:0.046

#### Normalized Reference Essay

In [12]:
reference_essay = EssayEditor(reference_essay.text)
reference_essay.normalise_text()
reference_essay.show_normalised_text()
reference_essay.show_edit_log()

dear local newspaper i think effects computers have on people are great learning skills or affects because they give us time to chat with friends or new people helps us learn about the globe astronomy and keeps us out of troble thing about dont you think so how would you feel if your teenager is always on the phone with friends do you ever time to chat with your friends or buisness partner about things well now theres a new way to chat the computer theirs plenty of sites on the internet to do so at organization one at organization two at caps one facebook myspace ect just think now while your setting up meeting with your boss on the computer your teenager is having fun on the phone not rushing to get off cause you want to use it how did you learn about other countrys or states outside of yours well i have by computer or internet its a new way to learn about what going on in our time you might think your child spends a lot of time on the computer but ask them so question about the economy sea floor spreading or even about the at date ones youll be surprise at how much he or she knows believe it or not the computer is much interesting then in class all day reading out of books if your child is home on your computer or at a local library its better than being out with friends being fresh or being perpressured to doing something they know isnt right you might not know where your child is at caps one forbidde in a hospital bed because of a driveby rather than your child on the computer learning chatting or just playing games safe and sound in your home or community place now i hope you have reached a point to understand and agree with me because computers can have great effects on you or child because it gives us time to chat with friends or new people helps us learn about the globe and believe or not keeps us out of troble thank you for listening

Normalised:
1: Essay converted to lower case successfully.
2: Symbols and spoken forms normalized successfully.
3: Cleaned- punctuation an unwanted spaces removed successfully.

## Component Testing

### Whisper (ASR) - Selecting the best model-parameter-configuration combination

In [14]:
import librosa
import os
from faster_whisper import WhisperModel
import time


size_compute_type_pairs= [
    ('small', 'int8_float16'), 
    ('small', 'float16'),      
    ('base', 'int8_float16'), 
    ('base', 'float16'),      
    ('medium', 'int8_float16'), 
    ('medium', 'float16'),  
]

#Get file and metadata
file_metadata= get_files_metadata("./data/audio/test")
if file_metadata:
    print(f"{file_metadata[0]['path']} accessed successfully.")
else:
    print("Error accessing file.")

#Load audio file and set sample rate
audio, rate = librosa.load(
file_metadata[0]["path"], 
sr=16000
)

#Get length of audio
duration = librosa.get_duration(y=audio, sr=rate)
if duration:
    print("Audio successfully loaded.")
else:
    print("Error loading audio.")

whisper_experiments = BatchDataOperator()#Stores results of experiments
    
for j, (m_size, c_type) in enumerate(size_compute_type_pairs, 1):
    
    #Start recording model loading time
    start_time = time.time()
    
    #load a model
    model = WhisperModel(
        model_size_or_path=m_size,
        device="cuda", 
        compute_type=c_type,
        cpu_threads=16,
    )
    #Calculate time taken to load model
    model_load_time = time.time() - start_time

    #Transcribe audio for beam sizes 1 to 5 
    for i in range(1, 6): 
        start_time = time.time()
        segments, info = model.transcribe(
            audio, 
            language="en",
            beam_size=i,
            vad_filter=True 
        )
        #Assemble transcription
        whisper_output = " ".join([segment.text for segment in segments])
        #Calculate transcription time
        inference_time = time.time() - start_time
        #Convert transcription string to EssayEditor Object for normalisation
        whisper_output = EssayEditor(whisper_output)
        #Normalise Essay
        whisper_output.normalise_text()

        #Calculate Error Rates
        error_rates = calculate_error_rates(reference_essay.get_text(), whisper_output.get_text())
    
        #IF both WER and CER below threshold evaluation passed else evaluation failed
        evaluation_status = ("pass" if error_rates["wer"] <= whisper_experiments.wer_threshold
                                 and error_rates["cer"] <= whisper_experiments.cer_threshold else "fail")
        
        whisper_experiments.update_eval_stats(evaluation_status, error_rates)
        
        #Store the details of the experiment as a dict
        details = {
            "Model Size": m_size,
            "Compute Type": c_type,
            "CPU Threads": 16,
            "Beam Size": i,
            "VAD Filter":True,
            "File Size": file_metadata[0]["size"], 
            "File Length":duration,
            "Model Load Time": round(model_load_time, 2),
            "Transcription Time": round(inference_time, 2),
            "Transcription": whisper_output.text,
            "WER": round(error_rates["wer"], 3),
            "CER": round(error_rates["cer"], 3),
            "Evaluation Status": evaluation_status
        }
        #Save experiment details to experiments list
        whisper_experiments.save_detail(details)
    print(f"Experiment {j}/6 completed")

data\audio\test\Daniella.wav accessed successfully.
Audio successfully loaded.
Experiment 1/6 completed
Experiment 2/6 completed
Experiment 3/6 completed
Experiment 4/6 completed
Experiment 5/6 completed
Experiment 6/6 completed

#### Display results for configurations

In [15]:
#Display Output as a dataframe
df = pd.DataFrame(whisper_experiments.details)
df= df[["Model Size", 
        "Compute Type", 
        "Beam Size", 
        "Model Load Time", 
        "Transcription Time", 
        "WER", 
        "CER", 
        "Evaluation Status"
       ]]
df.head()

,Model Size,Compute Type,Beam Size,Model Load Time,Transcription Time,WER,CER,Evaluation Status
0,small,int8_float16,1,1.6,5.88,0.100,0.050,fail
1,small,int8_float16,2,1.6,6.01,0.111,0.057,fail
2,small,int8_float16,3,1.6,6.28,0.094,0.046,fail
3,small,int8_float16,4,1.6,6.55,0.092,0.044,fail
4,small,int8_float16,5,1.6,6.68,0.119,0.074,fail

In [16]:
#Experiments 24 and 28 achieved the same transcription accuracy. However they differed greatly in the time taken to load the model. 
#In experiment 24, mixed-precision quantization - int8_float16 was used, along with a beam size of 5. This model took rougly 4 
#seconds to transcribe the audio. The model in experiment 28, with beam size 4 and compute_type set to float16, however, 
#took about 50% less time to load but was more than 3 times slower than the model in experiment 24. It is likely that the reduced 
#precision of int8 which produced smaller numerical values, as compared to float16, reduced the computation load resulting in 
#significantly less transcription time.

#### Display in ascending order of WER and CER accuracy

In [17]:
#Sort dataframe in ascending order
df_sorted = df.sort_values(by=["WER", "CER"], ascending = True)
#Show only columns needed for selecting model specification
df_sorted = df_sorted[["Model Size", "Compute Type", "Beam Size", "Model Load Time", "Transcription Time", "WER", "CER", "Evaluation Status"]]
df_sorted.head()

,Model Size,Compute Type,Beam Size,Model Load Time,Transcription Time,WER,CER,Evaluation Status
24,medium,int8_float16,5,3.71,14.19,0.089,0.038,pass
28,medium,float16,4,2.06,43.82,0.089,0.038,pass
22,medium,int8_float16,3,3.71,12.99,0.092,0.039,fail
29,medium,float16,5,2.06,41.39,0.092,0.039,fail
3,small,int8_float16,4,1.60,6.55,0.092,0.044,fail

### Whisper (ASR) Batch Transcription

In [18]:
#The model configuration chosen from the results of the previous experiments is:
# model_size = medium, beam_size=5, compute_type=int8_float16 
from faster_whisper import WhisperModel
import librosa
import time

#Get a list with all file paths, extensions, names in audio folder
files_metadata = get_files_metadata("./data/audio")

#Start recording model loading time
start_time = time.time()
#Load model
model = WhisperModel(
    model_size_or_path="medium",
    device="cuda", 
    compute_type="int8_float16",
    cpu_threads=16,
)
#Calculate model load time
model_load_time = time.time() - start_time

print(f"Whisper loaded successfully in {round(model_load_time,2)} seconds.")

whisper_batch = BatchDataOperator()

#Start Transcription Timer
start_time = time.time()

#Transcribe batch of audio files
for file in files_metadata:
    #Load audio file and set sample rate
    audio, rate = librosa.load(file["path"], sr=16000)
    
    #Get length of audio
    duration = librosa.get_duration(y=audio, sr=rate)
    segments, info = model.transcribe(
        audio, 
        language='en',
        beam_size=5,
        vad_filter=True 
    )
    #Assemble transcription
    whisper_output = " ".join([segment.text for segment in segments])

    #Convert to EssayEditor Object for normalisation
    whisper_output = EssayEditor(whisper_output)
    
    #Normalise Essay
    whisper_output.normalise_text()
    
    #Calculate Error Rates
    error_rates = calculate_error_rates(reference_essay.get_text(), whisper_output.get_text())

    #IF both WER and CER below threshold evaluation passed else evaluation failed
    evaluation_status = ("pass" if error_rates["wer"] <= whisper_batch.wer_threshold
                             and error_rates["cer"] <= whisper_batch.cer_threshold else "fail")
    
    whisper_batch.update_eval_stats(evaluation_status, error_rates)

    #Store the details of the transcription as a dict
    details = {
        "Student_ID": file["name"],
        "File Path": file["path"],
        "File Size": round(file['size'], 2), 
        "File Length":round(duration,2),
        "File Extension":file["extension"],
        "EssayEditor": whisper_output, 
        "WER": error_rates["wer"],
        "CER": error_rates["cer"],
        "Evaluation Status": evaluation_status
    }
    #Save transcription details and file properties to details list
    whisper_batch.save_detail(details)
    
#End of transcription, details saved to list
inference_time = time.time() - start_time
print(f"Whisper successfully transcribed {len(whisper_batch.details)} files in {round(inference_time/60,2)} minutes.")

Whisper loaded successfully in 3.75 seconds.
Whisper successfully transcribed 28 files in 5.83 minutes.


#### Batch Transcriptions Technical Details

In [19]:
#TODO: add to batchDataOPerator class, have if statement  deside what list to put based on image or audio
#     pass argument to show_technical_details(component = asr or ocr)
# cols = [blah blah ] if component == 'asr' else [blah, blah] 
df = pd.DataFrame(whisper_batch.details, index=range(1, len(whisper_batch.details)+1))
df= df[[
        "Student_ID",
        "File Path",
        "File Size", 
        "File Length",
        "WER",
        "CER",
        "Evaluation Status"
]]
df

,Student_ID,File Path,File Size,File Length,WER,CER,Evaluation Status
1,Aaliah,data\audio\Aaliah.wav,10.60,115.82,0.080556,0.032551,pass
2,Alliah,data\audio\Alliah.wav,11.98,130.87,0.077778,0.019210,pass
3,Amanda,data\audio\Amanda.wav,26.82,146.45,0.130556,0.057631,fail
4,AnonOne,data\audio\AnonOne.wav,13.48,147.23,0.097222,0.043757,fail
5,AnonThree,data\audio\AnonThree.wav,12.95,141.45,0.069444,0.024013,pass
6,AnonTwo,data\audio\AnonTwo.wav,11.73,139.42,0.105556,0.035752,fail
7,Bevan,data\audio\Bevan.wav,12.69,138.55,0.111111,0.053895,fail
8,Brice,data\audio\Brice.wav,16.48,180.01,0.144444,0.062433,fail
9,Daniella,data\audio\Daniella.wav,16.83,183.77,0.088889,0.037887,pass
10,Darnel,data\audio\Darnel.wav,19.29,210.69,0.180556,0.109392,fail
11,Darnell,data\audio\Darnell.wav,30.30,165.50,0.119444,0.060299,fail
12,Della,data\audio\Della.wav,10.87,118.72,0.155556,0.090181,fail
13,Gordon,data\audio\Gordon.wav,16.17,176.59,0.219444,0.131270,fail
14,Hannah,data\audio\Hannah.wav,12.01,131.18,0.130556,0.053895,fail
15,Kaelum,data\audio\Kaelum.wav,15.89,173.59,0.111111,0.048559,fail
16,Katelyn,data\audio\Katelyn.wav,22.41,133.24,0.147222,0.072572,fail
17,Kaylee,data\audio\Kaylee.wav,11.60,126.71,0.152778,0.069904,fail
18,Krista,data\audio\Krista.wav,14.30,170.02,0.069444,0.027215,pass
19,Michia,data\audio\Michia.wav,12.33,134.63,0.094444,0.046958,fail
20,Nasri,data\audio\Nasri.wav,15.45,168.75,0.122222,0.061366,fail
21,Neilage,data\audio\Neilage.wav,11.59,137.76,0.066667,0.024546,pass
22,Nubia,data\audio\Nubia.wav,12.13,132.46,0.102778,0.038954,fail
23,Reshan,data\audio\Reshan.wav,14.77,161.29,0.100000,0.036286,fail
24,Sheila,data\audio\Sheila.wav,15.85,173.08,0.100000,0.046958,fail
25,Shemar,data\audio\Shemar.wav,17.55,191.65,0.111111,0.052828,fail
26,Skyla,data\audio\Skyla.wav,15.33,167.49,0.088889,0.045891,pass
27,Tamera,data\audio\Tamera.wav,10.52,125.02,0.180556,0.120064,fail
28,Tia,data\audio\Tia.wav,10.60,115.82,0.080556,0.032551,pass

#### Descriptive Statistics

In [20]:
whisper_batch.show_wer_and_cer_stats()

            WER     CER
mean     11.57%   5.49%
median   10.83%   4.78%
min       6.67%   1.92%
max      21.94%  13.13%
std_dev   3.69%   2.77%

In [21]:
whisper_batch.show_eval_stats()

                      Batch Stats
wer passes                      8
wer fails                      20
wer pass percentage        28.57%
wer fail percentage        71.43%
cer passes                     15
cer fails                      13
cer pass percentage        53.57%
cer fail percentage        46.43%
total passes                    8
total fails                    20
total pass percentage      28.57%
total fail percentage      71.43%

#### Threshold Performance

In [22]:
whisper_batch.show_threshold_performance()

   Student_ID       WER       CER Evaluation Status
1     Neilage  0.066667  0.024546              pass
2   AnonThree  0.069444  0.024013              pass
3      Krista  0.069444  0.027215              pass
4      Alliah  0.077778  0.019210              pass
5      Aaliah  0.080556  0.032551              pass
6         Tia  0.080556  0.032551              pass
7    Daniella  0.088889  0.037887              pass
8       Skyla  0.088889  0.045891              pass
9      Michia  0.094444  0.046958              fail
10    AnonOne  0.097222  0.043757              fail
11     Reshan  0.100000  0.036286              fail
12     Sheila  0.100000  0.046958              fail
13      Nubia  0.102778  0.038954              fail
14    AnonTwo  0.105556  0.035752              fail
15      Bevan  0.111111  0.053895              fail
16     Kaelum  0.111111  0.048559              fail
17     Shemar  0.111111  0.052828              fail
18    Darnell  0.119444  0.060299              fail
19      Nasri  0.122222  0.061366              fail
20     Amanda  0.130556  0.057631              fail
21     Hannah  0.130556  0.053895              fail
22      Brice  0.144444  0.062433              fail
23    Katelyn  0.147222  0.072572              fail
24     Kaylee  0.152778  0.069904              fail
25      Della  0.155556  0.090181              fail
26     Darnel  0.180556  0.109392              fail
27     Tamera  0.180556  0.120064              fail
28     Gordon  0.219444  0.131270              fail

#### Representative Transcriptions

In [23]:
whisper_batch.show_representative_samples()

Student ID: Neilage
WER: 6.67%
CER: 2.45%
Evaluation Status: pass
dear local newspaper i think apex computers have on people are great learning skills or effects because they give us time to chat with friends or new people helps us learn about the globe astronomy and keeps us out of trouble think about dont you think so how would you feel if your teenager is always on the phone with friends do you ever tend to chat with your friends or base this partner about things well now theres a new way to chat the computer theres plenty of sites on the internet to do so at organization one at organization two at caps one facebook myspace etc just think now while youre setting up meeting with your boss on the computer your teenager is having fun on the phone not rushing to get off because you want to use it how did you learn about other countries or dates outside of yours well i have by computer or internet its a new way to learn about what going on in our time you might think your child spends a lot of time on the computer but ask them so question about the economy seafloor spreading or even about the at date once youll be surprised at how much he or she knows believe it or not the computer is much interesting than in class all day reading out of books if your child is home on your computer or at a local library its better than being out with friends being fresh or being peer pressured to doing something they know isnt right you might not know where your child is at caps two forbid in a hospital bed because of a driveby rather than your child on the computer learning chatting or just playing games safe and sound in your home or community place now i hope you have reached the point to understand and agree with me because computers can have great effects on you or child because it gives us time to chat with friends or new people helps us learn about the globe and believe or not keeps us out of trouble thank you for listening


Student ID: Daniella
WER: 8.89%
CER: 3.79%
Evaluation Status: pass
dear local newspaper i think effects computers have on people are great learning skills affects because they give us time to chat with friends new people helps us learn about the globe astronomy and keeps us out of trouble think about dont you think so how would you feel if your teenager is always on the phone with friends do you ever have time to chat with your friends or business partner about things well now theres a new way to chat the computer theres plenty of sites on the internet to do so organization one at organization two at caps one facebook myspace etc just think now while youre setting up meeting with your boss on the computer your teenager is having fun on the phone not rushing to get off because you want to use it how did you learn about other countries states outside of yours well i have my computer internet its a new way to learn about what is going on in our time you might think your child spends a lot of time on the computer but ask them so questions about the economy see for spreading or even about the dates youll be surprised at how much she knows believe it or not the computer is much interesting than in class all day reading out of books if your child is home on your computer or at a local library its better than being out with friends being fresh or being pressured to do something they know isnt right you might not know where your child is at caps two forbid in a hospital bed because of a driveby rather than your child on the computer learning chatting or just playing games safe and sound in your home or community place now i hope you have reached a point to understand and agree with me because computers can have great effects on you or child because it gives us time to chat with friends new people helps us learn about the globe and believe or not keeps us out of trouble thank you for listening


Student ID: AnonTwo
WER: 10.56%
CER: 3.58%
Evaluation Status: fail
dear local newspaper i think effects computers have on people are great learning skills or effects because they give us time to chat with friends or new people help us learn about the globe astronomy and keep us out of trouble think about it dont you think so how would you feel if your teenager is always on the phone with friends do you ever have time to chat with your friends or business partners about things well now theres a new way to chat the computer theres plenty of sites on the internet to do so at organization one at organization two at caps one facebook myspace etc just think now while youre setting up meetings with your boss on the computer your teenager is having fun on the phone not rushing to get off because you want to use it how did you learn about other countries or states outside of yours well i have my computer or internet its a new way to learn about what is going on in our time you might think your child spends a lot of time on the computer but ask them some questions about the economy see floors spreading or even about the update ones youll be surprised at how much she or he knows believe it or not the computer is much interesting than in class all day reading out of books if your child is home on your computer or at a local library its better than being out with friends being fresh or being prepressured to do something they know isnt right you might not know where your child is at caps two forbid in a hospital bed because of a driveby rather than your child on a computer learning chatting or just playing games safe and sound in your home or community place now i hope you have reached a point to understand and agree with me because computers can have great effects on you and your child because it gives us time to chat with friends or new people help us learn about the globe and believe it or not keep us out of trouble thank you for listening


Student ID: Hannah
WER: 13.06%
CER: 5.39%
Evaluation Status: fail
dear local newspaper i think effects computers have on people are great learning skills or effects because they give us time to chat with friends or new people helps us learn about the globe astronomy and keeps us out of trouble think about it dont you think so how would you feel if your teenager is always on the phone with friends do you ever have time to chat with your friends or business partners about things well now theres a new way to chat the computer theres plenty of sites on the internet to do so at organization one as organization to add caps one facebook my space etc just think about while youre setting up a meeting with your boss on the computer your teenager is having fun on the phone not rushing to get off because you want to use it how did you learn about other countries or states outside of yours well i have by the computer or internet its a new way to learn about whats going on in our time you might think your child spends a lot of time on the computer but ask them some questions about the economy see flow spreading or even about the date youll be surprised at how much he or he knows believe it or not the computer is much more interesting than in class or the reading out of books if your child is home on your computer or at a local library its because them being out with friends being fresh or being peer pressured to do something they know isnt right you might not know where your child is at caps to forbid in a hospital bed because of a drive by rather than your child on the computer learning chatting or just playing games safe and sound in your home or community place now i have i hope you have reached a point to understand and agree with me because computers can have great effects on you or your child because it gives us time to chat with friends or new people helps us learn about the globe and believe it or not keeps us out of trouble thank you for listening


Student ID: Gordon
WER: 21.94%
CER: 13.13%
Evaluation Status: fail
they are local newspapers i think if you are from these foreign people i agree with learning skills or effects because they give us time to chat with friends or new people helps us learn about the global astronomy and keeps us out of trouble think about it dont you think so how would you feel if katinja is always on the phone with friends do you ever have time to chat with your friends or business partner about things well now theres a new way to chat no computer they spend their time on the internet to do so organization to capsy facebook microsoft etc just speak now while youre setting up meeting with your boss on the computer your teenager is having fun on the phone not rushing to get off because you want to use it how did you learn about other countries or dates outside of yours well i have my computer or internet its a new way to learn about whats going on in our time you might think your child spends a lot of time on the computer but ask them so so question about the economy seafloor spreading or even about the dates youll be surprised at how much easier she knows believe it or not the computer is much more interesting than in class all day reading out of books if your child is home on your computer or at the local library its better than being persisted to do something they know isnt right you might not know where your child is caps to forbidden in hospital bed because of a driveby rather than your child on the computer learning chat you know just playing games safe and sound in your home or community place now i hope you have reached a point to understand and agree with me because this is going to have great effects on you or child because it gives us time to chat with friends or new people helps us learn about the group and believe it or not gives us out of trouble thank you for listening

### PaddleOCR (OCR) - Selecting the best model configuration

##### Notes

1. text_det_unclip_ratio (The Bounding Box Expander)
Why it matters for handwriting: This controls how much the bounding box expands around the detected text. Because cursive and handwriting have long tails and loops at the edges of words, a tight box will cut off characters, causing massive CER spikes.

Values to test: 1.5 (default), 1.8, and 2.0.

2. text_det_limit_side_len (Image Resolution Scaling)
Why it matters for handwriting: This resizes the image before passing it to the model. If a student wrote an entire essay on one page, the words are tiny. If the limit is too small, the image gets downscaled and pen strokes blur together. If it is too large, the system slows to a crawl and might detect background noise as text.

Values to test: 960 (standard default), 1280, and 1536 (high resolution for dense pages).

3. text_det_box_thresh (Faint Text Sensitivity)
Why it matters for handwriting: This determines how confident the model needs to be to declare a smudge or line is actually a word. Students often write lightly with pencils or faded pens. Lowering this threshold forces the model to capture faint writing that it might otherwise ignore.

Values to test: 0.4, 0.5, and 0.6 (default).

What to Freeze (Do NOT tune these)
You already made a great decision setting use_doc_orientation_classify, use_doc_unwarping, and use_textline_orientation to True. Because teenagers taking photos of essays will inevitably submit skewed, rotated, and warped images, you absolutely want those running on every test. Leave them fixed to True.

Leave text_rec_score_thresh alone. If you set this too high, the model will just drop words it isn't sure about, which artificially ruins your sentence structures before it even gets to DeBERTa.

#### Parameter configurations

In [24]:
#Import module
from paddleocr import PaddleOCR
import time

#Get sample file and extract metadata
file= get_files_metadata("./data/essays/test")
if file:
    print(f"{file[0]['name']}'s essay accessed successfully.")
else:
    print("Error accessing files.")

Kaylee's essay accessed successfully.

In [25]:
#Store parameters in lists
param_1_vals = [1.5, 1.8, 2.0] #text_det_unclip_ratio
param_2_vals = [960, 1280, 1536] #text_det_limit_side_len
param_3_vals = [0.4, 0.5, 0.6] #text_det_box_thresh

#Combine pairwise to obtain tuples of configurations
param_configs = list(zip(param_1_vals, param_2_vals, param_3_vals))

#Show parameter configurations
for i, (p1, p2, p3) in enumerate(param_configs, 1):
    print(f"Configuration {i}:", p1, p2, p3)

Configuration 1: 1.5 960 0.4
Configuration 2: 1.8 1280 0.5
Configuration 3: 2.0 1536 0.6

In [26]:
#Load the model and loop through configurations
ocr_batch = BatchDataOperator()
#TODO: Create an experiments function or class, that gets passed the type of operation and a 
for p1, p2, p3 in param_configs:
    
    ocr = PaddleOCR(
        #Fixed parameters
        text_detection_model_name="PP-OCRv6_medium_det",
        text_recognition_model_name="PP-OCRv6_medium_rec",
        engine="transformers",
        use_doc_orientation_classify=True,
        use_doc_unwarping=True,
        use_textline_orientation=True,
        #Variable parameters
        text_det_unclip_ratio = p1,
        text_det_limit_side_len=p2,
        text_det_box_thresh=p3
    )


    #Loop through each file

    prediction = ocr.predict(file[0]['path'])
    
    for result in prediction:
        sentences = result['rec_texts']
        #Combine into a single string
        essay = " ".join(sentence for sentence in sentences)
        #Convert to EssayEditor object
        ocr_output = EssayEditor(essay)
        #Normalise machine-readable textual output
        ocr_output.normalise_text()
        #Calculate Error Rates
        error_rates = calculate_error_rates(reference_essay.get_text(), ocr_output.get_text())
        #IF both WER and CER below threshold evaluation passed else evaluation failed
        evaluation_status = ("pass" if error_rates["wer"] <= ocr_batch.wer_threshold 
            and error_rates["cer"] <= ocr_batch.cer_threshold else "fail")
       
        ocr_batch.update_eval_stats(evaluation_status, error_rates)

        confidence_scores_list = []

        for (text, score) in zip(result["rec_texts"], result["rec_scores"]):
            confidence_scores_list.append(f"{score:.3f} | {text}")
            
        #Store the file properties and ocr process data as a dict
        details = { 
            "Student_ID":file[0]["name"], #required for show_representative_sample()
            "text_det_unclip_ratio": p1,
            "text_det_limit_side_len": p2,
            "text_det_box_thresh": p3, 
            "WER": error_rates["wer"],
            "CER": error_rates["cer"],
            "EssayEditor": ocr_output,
            "Confidence Scores": confidence_scores_list,
            "Evaluation Status": evaluation_status   
        }
        # Store details dict in batch object's details list
        ocr_batch.save_detail(details)

C:\Users\cowse\Code\AI\aes_notebook\env\Lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-LCNet_x1_0_doc_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_doc_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('UVDoc', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\UVDoc_safetensors`.

Loading weights:   0%|          | 0/295 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_textline_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_textline_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_det', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_det_safetensors`.

Loading weights:   0%|          | 0/350 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_rec', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_rec_safetensors`.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_doc_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_doc_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('UVDoc', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\UVDoc_safetensors`.

Loading weights:   0%|          | 0/295 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_textline_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_textline_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_det', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_det_safetensors`.

Loading weights:   0%|          | 0/350 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_rec', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_rec_safetensors`.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_doc_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_doc_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('UVDoc', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\UVDoc_safetensors`.

Loading weights:   0%|          | 0/295 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_textline_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_textline_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_det', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_det_safetensors`.

Loading weights:   0%|          | 0/350 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_rec', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_rec_safetensors`.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]

##### Display results of experiments

In [27]:
#Display Output as a dataframe
df = pd.DataFrame(ocr_batch.details)
df= df[[
        "text_det_unclip_ratio",
        "text_det_limit_side_len",
        "text_det_box_thresh", 
        "WER",
        "CER",
        "Evaluation Status"
       ]]
# df.head()
df

,text_det_unclip_ratio,text_det_limit_side_len,text_det_box_thresh,WER,CER,Evaluation Status
0,1.5,960,0.4,0.230556,0.067236,fail
1,1.8,1280,0.5,0.486111,0.266275,fail
2,2.0,1536,0.6,0.711111,0.463180,fail

#### Visually inspecting output for each configuration

In [28]:
for i in range(len(ocr_batch.details)):
    ocr_batch.details[i]["text_det_unclip_ratio"]
    ocr_batch.details[i]["text_det_limit_side_len"]
    ocr_batch.details[i]["text_det_box_thresh"]
    ocr_batch.details[i]["EssayEditor"].show_normalised_text()
    print("\n")

dear local newspaper i think effects computer have on people are great learning shills or affets because they gire us time to chat with friends or new people helps us karn about the globe astronomy and keeps us out of troblk thing about dont you think so how would you feel if your teenager is always on the phone with friends oo you ever time to chat with your friends or buisness parther about things well now theres a new way to chat the computer their is plerity of gites on the interned to do soorganizationi at organization twocapsifacebookmyspace ect justthinknowwileyouretingumeengwitourbo on the computer your teenager is having fun on the phone not rushin to get off cause you want to use it how did you leam about other countrys or states outside fyours well i have by computer or internetits a new way to learn about what going on in eurjime lou might think your child spends a lot of time on the computer but ask them so question about the economy sea floor spreadin or ever about the da te is youill be surprice at how much interesting he or she knows believe it or not the computer is mec interesting then in class all day reading out of books if your child is home on your computer or at a local librarg its bether than being out with friends being fresh or being perpressured to do something they know isrit right ou might not know where your child isat caps one forbide in a hospial bed because of a dry drireby rathor h then yor child on the computer learning chatting or just playing games sase and soend in your home or community plan now i hope you have reached a point to understend and agree with mebecause computers can hare grect effects on you or chil because it gives us time to chet with friends or new peaple help us learn aboud the globe and believe or not keeps us out of trouble thank cou der listening


dear lo ewaei tin eftomuter hae o peo are greeaninibehgeuto chat with friendsnew peoplehelps us karn about the globe castronomy and keeps us out of trobl thing about dont you think so how would you feel if your teenager is always on the phone with friends oo you ever time to chat wityour friendorbuisnesaai well now theres a new way to chat the computereir is plenity of sites on the interned to do so organizationi at organization twocapsifacebookmyspace ect juttnwe ontheomptrtegeihain to get off cause you want to use it how did you leam about other countrys or states auideourswell i have by compte or neraetlea eurtime ou might think your child spends a lot of time on the computerb soution aboutteonmyeo or even about the da te is youill be surprise at how much interesting he or she knows believe it or not the computer is mce interesting then in class all day reading out of books if your child is home on your computer or at a local librarg tsbetethan being out with friends being fresh or being perpressured to do something they know isnt right ou igho no whee your ldiap2 fbinabbefadrier thyarcnecomputerearninghtins playing games sase and sand inyor home or community pla now i hope you have reaa intounderanagee with mebecause computers can hare grect effects on you or chile because it gives us time to ct with friend ne peohelp us learn abou the globe and believe or not keeps us out of trouble thank cou der listening


dearlo ewaeri tinkefetehee regreanniheuto cha wth friendsew peehes u kar a th globe castronomy and keeps us out of trobk thing about dont you think so how would you feel if your teenager is always on the phone with friends oo you ever time tawtyofibuseaau wenotheresanewayto hathcomis plenity of sites on the interne to do so organizationi at organization twocapsifacebomyspace ec ei rehai to get aff cause you want to use it how did you leam abuecys or tte we ihvey cnat eurtime omighthinyouendat compsqutautt or even about the dateis youill be surprise at how much he or shenowbeieveitornothecompterise interesting then in cass all day reading out of books if your child is home on your computer ar at a local librarg betthanbeinguwitfriendbeingfresrbeing perpreetodosometingteyowisrtrigh heyap nabeaer acmeearing paingaeaeann ihaeratoe ith mebecause computers can hare gret effets on you or ie becue it gie us time to wth friedne peoehel us learn abou the globe and believe or not keeps us out of trouble thank cou der listening

##### Inspecting confidence scores

In [29]:
ocr_batch.details[0]["Confidence Scores"]

['0.990 | Dear local newspaper, I think effects computer have on people',
 '0.964 | are great learning shills/affets because they gire us time to',
 '0.981 | chat with friends/new people helps us karn about the globe',
 '0.976 | (astronomy) and keeps us out of troblk! Thing about!',
 "0.989 | Don't you think so? How would you feel if your teenager",
 '0.980 | is always on the phone with friends! Oo you ever time',
 '0.965 | to chat with your friends or buisness parther about things.',
 "0.969 | Well now there's a new way to chat the computer ,their is",
 '0.978 | plerity of gites on the interned to do so:@ORGANIZATIONI,',
 '0.921 | @ORGANIZATION2@CAPSI,facebOOk,mySpace ect.',
 '0.813 | Justthinknowwileyouretingumeengwitourbo',
 '0.884 | on the computer your teenager is having fun on the phone not rushin',
 '0.981 | to get off cause you want to use it. How did you leam',
 '0.943 | about other countrys/states outside fyours? Well I have by',
 '0.891 | computer/internet,its a new way to learn about what going on in',
 '0.972 | eurJime!',
 '0.948 | lou might think your child spends a lot of time on the',
 '0.951 | computer but ask them so question about the economy , sea floor spreadin',
 "0.973 | or ever about the @ DA TE I's youi'll be surprice at how much",
 '0.967 | interesting he/she knows. Believe it or not the computer is mec',
 '0.974 | interesting then in class all day reading out of books. If',
 '0.984 | your child is home on your computer or at a local librarg',
 "0.981 | it's bether than being out with friends being fresh or being",
 '0.947 | perpressured to do something they know isrit right.',
 '0.931 | ou might not know where your child is,@cAPS2 ',
 '0.849 | forbide in a hospial bed because of a dry drire-by. Rathor',
 '0.917 | h then yor child on the computer learning chatting or just',
 '0.957 | playing games, sase and soend in your home or community plan',
 '0.944 | Now I hope you have reached a point to understend and agree',
 '0.988 | with me,because computers can hare grect effects on you or chil',
 '0.948 | because it gives us time to chet with friends /new peaple ,help',
 '0.972 | us learn aboud the globe and believe or not keeps us out of',
 '0.935 | trouble. Thank cou der listening.']

### PaddleOCR-OCR Batch Detection and Recognition, TEST 1

In [30]:
#This model uses the configuration that produced the best results from the experiments
ocr = PaddleOCR(
    text_detection_model_name="PP-OCRv6_medium_det",
    text_recognition_model_name="PP-OCRv6_medium_rec",
    engine="transformers",
    use_doc_orientation_classify=True,
    use_doc_unwarping=True,
    use_textline_orientation=True,
    text_det_unclip_ratio = 1.5,
    text_det_limit_side_len=960,
    text_det_box_thresh=0.4
)
print("PaddleOCR loaded successfully.")

Creating model: ('PP-LCNet_x1_0_doc_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_doc_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('UVDoc', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\UVDoc_safetensors`.

Loading weights:   0%|          | 0/295 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_textline_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_textline_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_det', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_det_safetensors`.

Loading weights:   0%|          | 0/350 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_rec', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_rec_safetensors`.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]

PaddleOCR loaded successfully.

#### Text Detection, Recognition and Representation

In [31]:
#Get paths for all essays in sample
path_to_folder = "./data/essays"
files_list = get_files_metadata(path_to_folder)
print("Number of essays in sample:", len(files_list))

# Will store predictions for the batch 
ocr_batch = BatchDataOperator()
#Loop through files detecting and recognizing - predicting
for file in files_list:
    prediction = ocr.predict(file['path'])
    for result in prediction:
        sentences = result['rec_texts']
        #Combine into a single string
        essay = " ".join(sentence for sentence in sentences)
        #Convert to EssayEditor object
        ocr_output = EssayEditor(essay)
        #Normalise machine-readable textual output
        ocr_output.normalise_text()
        #Calculate Error Rates
        error_rates = calculate_error_rates(reference_essay.get_text(), ocr_output.get_text())
        #IF both WER and CER below threshold evaluation passed else evaluation failed
        evaluation_status = ("pass" if error_rates["wer"] <= ocr_batch.wer_threshold 
            and error_rates["cer"] <= ocr_batch.cer_threshold else "fail")
       
        ocr_batch.update_eval_stats(evaluation_status, error_rates)

        confidence_scores_list = []

        for (text, score) in zip(result["rec_texts"], result["rec_scores"]):
            confidence_scores_list.append(f"{score:.3f} | {text}")
            
        #Store the file properties and ocr process data as a dict
        details = {
            "Student_ID": file["name"],
            "File Path": file["path"],
            "File Size": round(file['size'], 2), 
            "File Extension":file["extension"],
            "EssayEditor": ocr_output, 
            "WER": error_rates["wer"],
            "CER": error_rates["cer"],
            "Confidence Scores": confidence_scores_list,
            "Evaluation Status": evaluation_status
        }
        # Store details dict in batch object's details list
        ocr_batch.save_detail(details)

Number of essays in sample: 28

#### Threshold Performance

In [32]:
ocr_batch.show_threshold_performance()

      Student_ID       WER       CER Evaluation Status
1          Nubia  0.111111  0.040021              fail
2          Skyla  0.166667  0.060299              fail
3         Tamera  0.197222  0.094984              fail
4        Darnell  0.205556  0.113661              fail
5        AnonTwo  0.222222  0.100854              fail
6         Kaylee  0.230556  0.067236              fail
7        AnonOne  0.233333  0.122199              fail
8        Neilage  0.238889  0.073106              fail
9         Shiela  0.238889  0.124333              fail
10       Katelyn  0.294444  0.193170              fail
11        Hannah  0.300000  0.200640              fail
12      Daniella  0.302778  0.118997              fail
13           Tia  0.316667  0.099787              fail
14        Alliah  0.327778  0.100854              fail
15       Kaelum   0.336111  0.157951              fail
16        Michia  0.336111  0.204909              fail
17        Krista  0.344444  0.116329              fail
18        Aaliah  0.361111  0.178762              fail
19        Amanda  0.372222  0.175560              fail
20  Gordon essay  0.394444  0.136073              fail
21         Nasri  0.411111  0.197439              fail
22     AnonThree  0.413889  0.250267              fail
23         Bevan  0.413889  0.167022              fail
24   Della essay  0.422222  0.293490              fail
25        Reshan  0.447222  0.160619              fail
26         Brice  0.458333  0.203308              fail
27        Darnel  0.463889  0.266809              fail
28        Shemar  0.894444  0.751334              fail

#### Descriptive Statistics

In [33]:
ocr_batch.show_wer_and_cer_stats()

            WER     CER
mean     33.77%  17.04%
median   33.19%  14.70%
min      11.11%   4.00%
max      89.44%  75.13%
std_dev  14.14%  12.78%

In [34]:
ocr_batch.show_eval_stats()

                      Batch Stats
wer passes                      0
wer fails                      28
wer pass percentage         0.00%
wer fail percentage       100.00%
cer passes                      1
cer fails                      27
cer pass percentage         3.57%
cer fail percentage        96.43%
total passes                    0
total fails                    28
total pass percentage       0.00%
total fail percentage     100.00%

#### Representative Extractions

In [35]:
ocr_batch.show_representative_samples()

Student ID: Nubia
WER: 11.11%
CER: 4.00%
Evaluation Status: fail
dear local newspaper i think effects computers have on people are great learning skills or affects because they give us time to chat with friends or new people helps us learn about the global castronomy and keeps us out of troble thing about dont you think so how would you feel if your teenager is always on the phone with friends do you ever time to chat with your friends or buis partner about things well now theres a new way fo chat the computer theirs plenty of sites on the internet to do so organization1 organization 2 caps1 facebook myspace ect just think now while your setting up meeting with your bass on the computer your teenager is having fun on the phone not rushing to get off cause you want to use it tow did you learn about other countries or states outside of yours well i have by computer or internet its a new way to learn about what going on in eur time you might think your child speaks alot of the time on the computer but ask them so question about the economy sea floor spreading or even about the datels youll be surprised at how much he or she knows believe it or not the computer is much interesting then in class all day reading out of books if your child is home on your computer or at a local library its better than being out with friends being fresh or being perpressured to do something they know ist right you might not know where your child is caps2 forbidde in the hospital bed because of a driveby rather than your child on a eomputer leerning chatting or just playing games safe and sound in your home or comntinity place now i hepe you have reached a point to understand and agree with me because computers can have great effects on you or child becaus it gives us time to chat with friends or new people help us learn about the globe and believe or not keeps us out of troble thank youfor listenina


Student ID: AnonOne
WER: 23.33%
CER: 12.22%
Evaluation Status: fail
computers have on people are great etrects learning skills or alfects because they give us time to chat with freinds or new people helps us learn about the globe astronomy and keeps cus out of froable troble thing about 6 dont you thinlk so how would you feel if your teenager is always on the phone with freinds do yow ever time to chat with you freinds or buisness partner aebout things well now theres a new way to chat the computer theirs plenty of sites on the internet to do so organization 1 organizaiion2caps facebook myspace ect just think now while yow setting up meeting with your boss on the computer your teenager is having fun on the phone not rushing to get off cause you want to use it hou dod you learn about ather countris istates outsicde of yours well i have by computer linternet its a new way to learn about what going on in cu time you might think you child spends a lot of time on the computer but ask them so question about the economy sea floor spreading or even about the date1s youll be suprise at how much helshe kknows believe it or not the computer is much interesting then in class all day reading out of bocks if you child is home on your computer or at a local library its better than being out with freinds being freshs or being perpressred to doing something they know isnt right you might not know where yow child is caps2 forbidde ina hospital bed because of a drive by rather than yow child on the cemputer learning chatting or just playing games safe and so now i hope you have reached a paint to understand and agree with me becacest computers can have great effects on you or child because coripaters can it gives us time to chat with freinds inew pecple helps cus learn about the globe and beleve or heeps us out of troble


Student ID: Alliah
WER: 32.78%
CER: 10.09%
Evaluation Status: fail
dear local neuspaper i think effecb compulers have on people are great lecrning skillslaffects because trey glve us time to chat cunth friends or new peoplehelp us learn abaut the globe costronemy and kecp uo out of troble thing about dont you think so hou wwould you feel if your teencger o always on the phone with frends po you euer time to chat with your friends or busines partner about things kell now theres a nam way to chet the computertheirs plenty of sites on the internet to do so organization1 organization 2 at caps one pakebook myspacc etc just think nou wtile your setting up meeting cwith your boos on the computer your teenager is houing fun on the phone not ruobing to get off cause you want to coe it how did you learn about other countryp or states outside of yours klell i hove by computerlinternet its a new way to learn abat luhdt going on in our time you might think your chith spends a lot op time onthe computer but cok them so question about the ecoromy bea floor spreading or euen about the date1s youll be supnse at haci much helshe knaus believe it or not the computer o much interesting han in class all day rending out of book ip your child is home on your computer or at a local librairy its bietter than bang out vcouth prends being fresh or baing prepressured to dang somdhing they knau ont right you might not know where your child is caps2 fobickle in a hospital bed becouse of a driueby bather than yor child on the computer korning chotting or just playing games safe and sound in your home or commanity k now i hope you hove reached a poaint to understand and cgree cuith me because computers con hove great effets on you or child becouse it gives us time to chat with friendb or nee peopk hdps us learn abat the globe and brhece or not keops is out op troble thonk vou por listenin


Student ID: Nasri
WER: 41.11%
CER: 19.74%
Evaluation Status: fail
people are great learning skitislaftets because they e us time to chat with friends or new peoplehelp us asn abont the globe lastronamy and keeps us aut of e troble thing abont dont you think so how would you feel it your teenager is always on the phage with friends do you ever time to chat youe friends or business buisness patner abent things well now theres a pew way to that the compowter theirs plenty of sites on the intend to do so organizationi organization2 capsi facebook myspace ect just think non while yow sething up meting wth your bess on he compnter your teenager is hawing hun on the phone ne rushing to get off lause you wart to use it how did you learn about other countrys or states ontsit fyouswell iheby comterintentsane to about what going en in our time you might think your child spends a lot of lime on the computer but ask them so question about the economy sea ploor spreating or even abbort the dateis yow be a sugrist at how much he knan he or she knows beliere or not the comater is much interesting then in lass all day ceading ont of boeks if your child is home on your compwter at a local library its better than being out with frier being presh or being perpressured to doing something theg sni right you might not know where you child is aps2 rbidde in a hospit bed because of a drive by rether then your whold on the comprter lear chatting or just playing games safe and sound your home or community phace now i bope youg have seuched a paint to and agre mith me baause camputers can great ethets on you or ase gimetawit rie abot the globe and beliere itrnotk of troblethank yon for listening


Student ID: Shemar
WER: 89.44%
CER: 75.13%
Evaluation Status: fail
d or hc tdhy cxthmz x 2oson i h 4 entoret to a mes wey to learn annt s going on in ons timne you uight think var dhid sad alate of tame an the iter oat ash them 2o queton aront the ceaony flor soredg or awen aut hudaks youll be aurpried at how much he or she iawbeliave tarnot anuter o mch intreoting n in dlars all dey reading ont of broods if your cild sit have a eth eth thy o rihyaght t whear ehioe cena oh r sound in your hore or communty flace seao eeasena bee i e th t ri peohe thae or not bups o out of froute phank yom cor loolag

##### Visual inspection of output with a low CER and relatively low WER

In [53]:
#Kaylee #5
print("Student:", ocr_batch.details[5]["Student_ID"])
print("WER:", f"{ocr_batch.details[5]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[5]['CER']:.2%}")
ocr_batch.details[5]["EssayEditor"].show_normalised_text()
print("\n")

#Neilage #7
print("Student:", ocr_batch.details[7]["Student_ID"])
print("WER:", f"{ocr_batch.details[7]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[7]['CER']:.2%}")
ocr_batch.details[7]["EssayEditor"].show_normalised_text()

Student: Kaylee
WER: 23.06%
CER: 6.72%
dear local newspaper i think effects computer have on people are great learning shills or affets because they gire us time to chat with friends or new people helps us karn about the globe astronomy and keeps us out of troblk thing about dont you think so how would you feel if your teenager is always on the phone with friends oo you ever time to chat with your friends or buisness parther about things well now theres a new way to chat the computer their is plerity of gites on the interned to do soorganizationi at organization twocapsifacebookmyspace ect justthinknowwileyouretingumeengwitourbo on the computer your teenager is having fun on the phone not rushin to get off cause you want to use it how did you leam about other countrys or states outside fyours well i have by computer or internetits a new way to learn about what going on in eurjime lou might think your child spends a lot of time on the computer but ask them so question about the economy sea floor spreadin or ever about the da te is youill be surprice at how much interesting he or she knows believe it or not the computer is mec interesting then in class all day reading out of books if your child is home on your computer or at a local librarg its bether than being out with friends being fresh or being perpressured to do something they know isrit right ou might not know where your child isat caps one forbide in a hospial bed because of a dry drireby rathor h then yor child on the computer learning chatting or just playing games sase and soend in your home or community plan now i hope you have reached a point to understend and agree with mebecause computers can hare grect effects on you or chil because it gives us time to chet with friends or new peaple help us learn aboud the globe and believe or not keeps us out of trouble thank cou der listening


Student: Neilage
WER: 23.89%
CER: 7.31%
dear local newspaper i thinlh effects computers have on people are great learning skills or appects becouse they give us time to chat with friends or riew peaple helps is leam about the gldbelastronomy and keeps us out of trode thing about dont you think so how wlould you fed if your teenager is always on the phone with friends do you ever time to chat with your friends or businegs partners about thingswell now theres a new way to chat the computer theirs plents of sites on the intemet to do so at organization oneorganizatioll2capsfacebook mnyspaceect just think now while your setting up metting with your boss on the computer your teenager 1s having fun on the phone not rushing to get off couse you want to use it hows did you learn about other countrys or states outslde of ypurs well i have by compufer or intemetits a new way to learn about what going on in our time you might think sour child spends a lot of time on the computer but ask them so question about the economy sea ploor spreading or even about the dateis yowll be simprise at how much she he knows believe if or not the computer is much interester then in class all day reading out of bodks if cour child is hame on your compufer or at a looal library its better than being out with friends being freshor being perpressured to doing something they linow lont nght you might not kinow where your child is caps 2 forbidde in a hanspital bed because of a drive by rather than your child on the computer learning chattin or just plaiyng gamessape and sound in yaur home or communitesplade now i hope uou have readhed a point to understand and acree with me becase computers can have great effects on you or child becacuse it gives us hime to chat with friends or new people helps us leam aba the globe and believe or not heeps us out of trode ymoliatonine

#### Confidence Scores

In [37]:
#Lowest WER and CER scores
print("Student:", ocr_batch.details[0]["Student_ID"])
ocr_batch.details[0]["Confidence Scores"]

Student: Nubia

['0.989 | Dear local newspaper, I think effects computers have on',
 '0.999 | people are great learning skills/affects because they give us',
 '0.998 | time to chat with friends/new people, helps us learn about the',
 '0.998 | global Castronomy) and keeps us out of troble! Thing about!',
 '0.985 | Dont you think so? How would you feel if your teenager is',
 '0.996 | always on the phone with friends! Do you ever time to chat',
 '0.985 | with your friends or buis partner about things. well now-',
 "0.997 | there's a new way fo chat the computer, theirs plenty of sites",
 '0.960 | on the internet to do So: @ ORGANIZATION1, @ ORGANIZATION 2,',
 '0.965 | @ caps1, facebook, myspace ect.',
 '0.993 | Just think now while your setting up meeting with your bass',
 '0.996 | on the computer, your teenager is having fun on the phone not rushing',
 '0.982 | to get off cause you want to use it. tow did you learn about other',
 '0.988 | countries/states outside of yours? Well I have by computer/internet,',
 "0.997 | it's a new way to learn about what going on in eur time!",
 '1.000 | You might think your child speaks alot of the time on the computer,',
 '0.997 | but ask them so question about the economy, sea floor spreading or',
 "0.989 | even about the @ DATEl's you'll be surprised at how much he/she",
 '0.988 | knows: Believe it or not the computer is much interesting then in class',
 '0.987 | all day reading out of books: if your child is home on your computer',
 '0.985 | or at a local library, its better than being out with friends being',
 '1.000 | fresh or being perpressured to do something they know ist right',
 '0.989 | You might not know where your child is @ caps2 forbidde in the',
 '0.982 | hospital bed because of a driveby, Rather than your child on a',
 '0.986 | eomputer leerning, chatting or just playing games. safe and sound in',
 '0.990 | your home or comntinity place.',
 '0.991 | Now I hepe you have reached a point to understand and agree with',
 '0.973 | me, because computers, can have great effects on you or child becaus.',
 '0.997 | it gives us time to chat with friends/new people, help us learn about',
 '1.000 | the globe and believe or not keeps us out of troble. Thank youfor',
 '0.937 | listenina.']

In [38]:
#Highest WER and CER scores
print("Student:", ocr_batch.details[-1]["Student_ID"])
ocr_batch.details[-1]["Confidence Scores"]

Student: Shemar

['0.644 | D/',
 '0.388 | HC',
 '0.535 | tDHy ',
 '0.536 | cxthmz',
 '0.677 | X',
 '0.642 | 2oson@@',
 '0.337 | I ',
 '0.534 | H?',
 '0.248 | 4',
 '0.830 | entoret, to a mes wey to learn annt s going on in ons timne',
 '0.717 | You uight think var dhid sad alate of tame an the iter oat ash them 2o queton aront the ceaony',
 "0.666 | flor soredg or awen aut Hu@dak's you'll be aurpried at how much he/she iaw.Beliave tarnot",
 '0.805 | anuter o mch intreoting n in dlars all dey reading ont of broods If your cild sit have a',
 '0.411 | [,eth ',
 '0.533 | eth thy o rihYaght t whear ehioe Cena oh',
 '0.386 | R',
 '0.923 | sound in your hore or communty flace',
 '0.440 | seao eeasena',
 '0.517 | bee i e th t ri peohe thae',
 '0.828 | or not bups o out of froute. Phank yom Cor loolag']

### PaddleOCR-OCR Batch Detection and Recognition, TEST 2

In [39]:
#This model uses the configuration that produced the best results from the experiments
ocr = PaddleOCR(
    text_detection_model_name="PP-OCRv6_medium_det",
    text_recognition_model_name="PP-OCRv6_medium_rec",
    engine="transformers",
    use_doc_orientation_classify=True,
    use_doc_unwarping=True,
    use_textline_orientation=True,
    text_det_unclip_ratio = 1.5,
    text_det_limit_side_len=960,
    text_det_box_thresh=0.4
)
print("PaddleOCR loaded successfully.")

Creating model: ('PP-LCNet_x1_0_doc_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_doc_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('UVDoc', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\UVDoc_safetensors`.

Loading weights:   0%|          | 0/295 [00:00<?, ?it/s]

Creating model: ('PP-LCNet_x1_0_textline_ori', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-LCNet_x1_0_textline_ori_safetensors`.

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_det', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_det_safetensors`.

Loading weights:   0%|          | 0/350 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_rec', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\cowse\.paddlex\official_models\PP-OCRv6_medium_rec_safetensors`.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]

PaddleOCR loaded successfully.

#### Text Detection, Recognition and Representation

In [48]:
#Get paths for all essays in sample
path_to_folder = "./data/essays"
files_list = get_files_metadata(path_to_folder)
print("Number of essays in sample:", len(files_list))

# Will store predictions for the batch 
ocr_batch2 = BatchDataOperator()

#Adjust WER and CER thresholds
ocr_batch2.set_wer_threshold(0.2)
ocr_batch2.set_cer_threshold(0.08)

#Loop through files detecting and recognizing - predicting
for file in files_list:
    prediction = ocr.predict(file['path'])
    for result in prediction:
        sentences = result['rec_texts']
        #Combine into a single string
        essay = " ".join(sentence for sentence in sentences)
        #Convert to EssayEditor object
        ocr_output = EssayEditor(essay)
        #Normalise machine-readable textual output
        ocr_output.normalise_text()
        #Calculate Error Rates
        error_rates = calculate_error_rates(reference_essay.get_text(), ocr_output.get_text())
        #IF both WER and CER below threshold evaluation passed else evaluation failed
        evaluation_status = ("pass" if error_rates["wer"] <= ocr_batch2.wer_threshold 
            or error_rates["cer"] <= ocr_batch2.cer_threshold else "fail")
       
        ocr_batch2.update_eval_stats(evaluation_status, error_rates)

        confidence_scores_list = []

        for (text, score) in zip(result["rec_texts"], result["rec_scores"]):
            confidence_scores_list.append(f"{score:.3f} | {text}")
            
        #Store the file properties and ocr process data as a dict
        details = {
            "Student_ID": file["name"],
            "File Path": file["path"],
            "File Size": round(file['size'], 2), 
            "File Extension":file["extension"],
            "EssayEditor": ocr_output, 
            "WER": error_rates["wer"],
            "CER": error_rates["cer"],
            "Confidence Scores": confidence_scores_list,
            "Evaluation Status": evaluation_status
        }
        # Store details dict in batch object's details list
        ocr_batch2.save_detail(details)

Number of essays in sample: 28

#### Threshold Performance

In [49]:
ocr_batch2.show_threshold_performance()

      Student_ID       WER       CER Evaluation Status
1          Nubia  0.111111  0.040021              pass
2          Skyla  0.166667  0.060299              pass
3         Tamera  0.197222  0.094984              pass
4        Darnell  0.205556  0.113661              fail
5        AnonTwo  0.222222  0.100854              fail
6         Kaylee  0.230556  0.067236              pass
7        AnonOne  0.233333  0.122199              fail
8        Neilage  0.238889  0.073106              pass
9         Shiela  0.238889  0.124333              fail
10       Katelyn  0.294444  0.193170              fail
11        Hannah  0.300000  0.200640              fail
12      Daniella  0.302778  0.118997              fail
13           Tia  0.316667  0.099787              fail
14        Alliah  0.327778  0.100854              fail
15       Kaelum   0.336111  0.157951              fail
16        Michia  0.336111  0.204909              fail
17        Krista  0.344444  0.116329              fail
18        Aaliah  0.361111  0.178762              fail
19        Amanda  0.372222  0.175560              fail
20  Gordon essay  0.394444  0.136073              fail
21         Nasri  0.411111  0.197439              fail
22     AnonThree  0.413889  0.250267              fail
23         Bevan  0.413889  0.167022              fail
24   Della essay  0.422222  0.293490              fail
25        Reshan  0.447222  0.160619              fail
26         Brice  0.458333  0.203308              fail
27        Darnel  0.463889  0.266809              fail
28        Shemar  0.894444  0.751334              fail

#### Descriptive Statistics

In [50]:
ocr_batch2.show_wer_and_cer_stats()

            WER     CER
mean     33.77%  17.04%
median   33.19%  14.70%
min      11.11%   4.00%
max      89.44%  75.13%
std_dev  14.14%  12.78%

In [51]:
ocr_batch2.show_eval_stats()

                      Batch Stats
wer passes                      5
wer fails                      23
wer pass percentage        17.86%
wer fail percentage        82.14%
cer passes                      5
cer fails                      23
cer pass percentage        17.86%
cer fail percentage        82.14%
total passes                    5
total fails                    23
total pass percentage      17.86%
total fail percentage      82.14%

In [54]:
#TODO: have user pass in either a single or index of file details or a list to display several
#Kaylee #5
print("Student:", ocr_batch.details[5]["Student_ID"])
print("WER:", f"{ocr_batch.details[5]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[5]['CER']:.2%}")
ocr_batch.details[5]["EssayEditor"].show_normalised_text()
print("\n")

#Neilage #7
print("Student:", ocr_batch.details[7]["Student_ID"])
print("WER:", f"{ocr_batch.details[7]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[7]['CER']:.2%}")
ocr_batch.details[7]["EssayEditor"].show_normalised_text()
print("\n")

#Neilage #7
print("Student:", ocr_batch.details[0]["Student_ID"])
print("WER:", f"{ocr_batch.details[0]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[0]['CER']:.2%}")
ocr_batch.details[0]["EssayEditor"].show_normalised_text()

print("\n")

#Neilage #7
print("Student:", ocr_batch.details[1]["Student_ID"])
print("WER:", f"{ocr_batch.details[1]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[1]['CER']:.2%}")
ocr_batch.details[1]["EssayEditor"].show_normalised_text()

print("\n")

#Neilage #7
print("Student:", ocr_batch.details[2]["Student_ID"])
print("WER:", f"{ocr_batch.details[2]['WER']:.2%}")
print("CER:", f"{ocr_batch.details[2]['CER']:.2%}")
ocr_batch.details[2]["EssayEditor"].show_normalised_text()

Student: Kaylee
WER: 23.06%
CER: 6.72%
dear local newspaper i think effects computer have on people are great learning shills or affets because they gire us time to chat with friends or new people helps us karn about the globe astronomy and keeps us out of troblk thing about dont you think so how would you feel if your teenager is always on the phone with friends oo you ever time to chat with your friends or buisness parther about things well now theres a new way to chat the computer their is plerity of gites on the interned to do soorganizationi at organization twocapsifacebookmyspace ect justthinknowwileyouretingumeengwitourbo on the computer your teenager is having fun on the phone not rushin to get off cause you want to use it how did you leam about other countrys or states outside fyours well i have by computer or internetits a new way to learn about what going on in eurjime lou might think your child spends a lot of time on the computer but ask them so question about the economy sea floor spreadin or ever about the da te is youill be surprice at how much interesting he or she knows believe it or not the computer is mec interesting then in class all day reading out of books if your child is home on your computer or at a local librarg its bether than being out with friends being fresh or being perpressured to do something they know isrit right ou might not know where your child isat caps one forbide in a hospial bed because of a dry drireby rathor h then yor child on the computer learning chatting or just playing games sase and soend in your home or community plan now i hope you have reached a point to understend and agree with mebecause computers can hare grect effects on you or chil because it gives us time to chet with friends or new peaple help us learn aboud the globe and believe or not keeps us out of trouble thank cou der listening


Student: Neilage
WER: 23.89%
CER: 7.31%
dear local newspaper i thinlh effects computers have on people are great learning skills or appects becouse they give us time to chat with friends or riew peaple helps is leam about the gldbelastronomy and keeps us out of trode thing about dont you think so how wlould you fed if your teenager is always on the phone with friends do you ever time to chat with your friends or businegs partners about thingswell now theres a new way to chat the computer theirs plents of sites on the intemet to do so at organization oneorganizatioll2capsfacebook mnyspaceect just think now while your setting up metting with your boss on the computer your teenager 1s having fun on the phone not rushing to get off couse you want to use it hows did you learn about other countrys or states outslde of ypurs well i have by compufer or intemetits a new way to learn about what going on in our time you might think sour child spends a lot of time on the computer but ask them so question about the economy sea ploor spreading or even about the dateis yowll be simprise at how much she he knows believe if or not the computer is much interester then in class all day reading out of bodks if cour child is hame on your compufer or at a looal library its better than being out with friends being freshor being perpressured to doing something they linow lont nght you might not kinow where your child is caps 2 forbidde in a hanspital bed because of a drive by rather than your child on the computer learning chattin or just plaiyng gamessape and sound in yaur home or communitesplade now i hope uou have readhed a point to understand and acree with me becase computers can have great effects on you or child becacuse it gives us hime to chat with friends or new people helps us leam aba the globe and believe or not heeps us out of trode ymoliatonine


Student: Nubia
WER: 11.11%
CER: 4.00%
dear local newspaper i think effects computers have on people are great learning skills or affects because they give us time to chat with friends or new people helps us learn about the global castronomy and keeps us out of troble thing about dont you think so how would you feel if your teenager is always on the phone with friends do you ever time to chat with your friends or buis partner about things well now theres a new way fo chat the computer theirs plenty of sites on the internet to do so organization1 organization 2 caps1 facebook myspace ect just think now while your setting up meeting with your bass on the computer your teenager is having fun on the phone not rushing to get off cause you want to use it tow did you learn about other countries or states outside of yours well i have by computer or internet its a new way to learn about what going on in eur time you might think your child speaks alot of the time on the computer but ask them so question about the economy sea floor spreading or even about the datels youll be surprised at how much he or she knows believe it or not the computer is much interesting then in class all day reading out of books if your child is home on your computer or at a local library its better than being out with friends being fresh or being perpressured to do something they know ist right you might not know where your child is caps2 forbidde in the hospital bed because of a driveby rather than your child on a eomputer leerning chatting or just playing games safe and sound in your home or comntinity place now i hepe you have reached a point to understand and agree with me because computers can have great effects on you or child becaus it gives us time to chat with friends or new people help us learn about the globe and believe or not keeps us out of troble thank youfor listenina


Student: Skyla
WER: 16.67%
CER: 6.03%
dear local newspaper i think effects computers have on people are great learning skills or affects because they oive us time to chat with friends or new people helps us learn about the globe castronomy and keeps us out o rouble thing about dont you think so how would you feel if your teenager is always on the phone with friends to you ever time to chat with your friends or b buioness partner about things well now theres a new way to chat the computer theirs plenty of sites on the intemet to do so organization 1 organizatio 2 capsi facebook myppace est just think now while your setting up meeting with your boss on the computer your teenager is having fun on the phone not rushing to get of cause you want to use it how did you learn about other countrys i stat outside of yours well i have by computer linternet its a new way o learn about what going on in aur time you might think your child gends alot of time on the computers it ask them so question about he economy sea floor spreading or pen about the date is yaill be surprise at how much hel she knows believe it or not the computer is ruch interesting then in class all day reading out of book if your hild is home on your computer or at bcal library its better than being i with friends being fresh or being erpressured to ding doing something they know isnt right you might not know where your child is caps 2 forbidde n a hospital bed because of a driveby hather than your child on the computer earning chating or just playing games safe and sound in your home or community place now i hope you have reached a point to understand and agree with me because comprters can have great effects on you or child because it gives us time to chat with friends new people helps us leam about the glabe and believe or not keeps us out f troble thankuou


Student: Tamera
WER: 19.72%
CER: 9.50%
effects because they give us fime to chat with friends or hew peple helps us learn about the globe gastronomy and keeps us out of fioble thing jabout dont you think so how would y you feed if your teeneager is always on the phone with friends do you ever fime to chat with your forends or buisness partner about things well now theres a new way to chat the computer theirs plenty of sites on the internet to do so at organization one organizationz at caps one facebook my space etc 7 just think now while your setting up meeting with your boss on the computer your teenager is having fun on the phane hot rushing to get ff cause you want to use if houdid you leam about other country or states outside of yours well well i have by computer intemet its a new way to lean about what going on in ourtime you might think you child spends to much time on the computer but ask them so question about the economy sea floor spreading or even about the date1s youllj be surprised at how much he or she kinous believe it or not the computer is much interesting then in class all day reading out of books if your child is home on your computer or at a local library its better that being out with friends being fresh or being perpressured to do something they know isht right you might not kinow wbere your child is at caps one forbidde in a hospital bed because of a drive by rather than your child on the computer learning chatting or gust playing games safe and sound in your home or community place point now i hope you have reached a point to understand and agree with me because computers can have great effects on you or child because it gives us time to chat with friends i new people helps us learn about the globle and believe or not keeps us out of trole thank you fo listenina